# Generated by Django 5.0.1 on 2024-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_vacancy_area_name_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('BYR', models.FloatField(blank=True, null=True)),
                ('USD', models.FloatField(blank=True, null=True)),
                ('EUR', models.FloatField(blank=True, null=True)),
                ('KZT', models.FloatField(blank=True, null=True)),
                ('UAH', models.FloatField(blank=True, null=True)),
                ('AZN', models.FloatField(blank=True, null=True)),
                ('KGS', models.FloatField(blank=True, null=True)),
                ('UZS', models.FloatField(blank=True, null=True)),
                ('GEL', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
