# Generated by Django 5.0.1 on 2024-01-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_currencyrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
