# Generated by Django 5.0.1 on 2024-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_sitesection_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='url_path',
            field=models.CharField(max_length=255),
        ),
    ]
